### PR TITLE
Document systemd-devel package requirement

### LINKED ISSUE #1865: The geopm-service.spec.in file does not specify BuildRequires for libsystemd.so and headers
The ServiceIOGroup requires libsystemd.so and sdbus.h.  Need to update the spec file to reflect this requirement for both RHEL and SLES flavors of package names.

### PR DESCRIPTION
**Pull request by cmcantalupo**
- Fixes #1865 from github issues.

### CODE REVIEW

**Comment by fkeceli** [comment]
Looks good.

**Review by fkeceli — DISMISSED** [review]
Looks good.

**Review by bgeltz — CHANGES_REQUESTED** [review]
Configure time check to make sure systemd-devel is present if ENABLE_SYSTEMD was specified?

**Comment by cmcantalupo** [comment]
@bgeltz 

https://github.com/geopm/geopm/blob/geopm-service/service/configure.ac#L216-L223

**Review by bgeltz — APPROVED** [review]

**Pull request merged**
